### ISSUE TITLE
Update to Swift 3

### ISSUE THREAD

**Issue by evfrenkel** [nutritionfactsorg/daily-dozen-ios#13]
Should be pretty easy. I am willing to take this on.

**Comment by mnemonicflow** [comment]
@innerfish said [here](https://github.com/nutritionfactsorg/daily-dozen-ios/issues/14#issuecomment-275422658) that 

> I've been working on a rewrite of the iOS app in Swift pretty much as a
> solo project.

You should talk with him. 

@innerfish Do you plan to put your Swift rewrite code in a new branch in this repo so that people can start contributing?

**Comment by innerfish** [comment]
I'm looking forward to help on this project. Converting to Swift 3.0 would be great. (Note that we do use a couple of open source libraries that may also need updating.) Do you all have access to the current Swift development branch?

I created a slack team for easier communication. Please share your email addresses with me for an invite.

Will

**Comment by evfrenkel** [comment]
@innerfish I'm on the official slack, but if there is another slack you are using can you invite me? comrad@gmail.com

What do you mean by current swift development branch?

**Comment by christirichards** [comment]
I'm going to go ahead and close this issue.

Please use the NF Slack channel for communications.  Since I'm talking to both of you in email, I can follow up on what's next there and make an announcement later, if needed.
