### ISSUE TITLE
Add three "servings" for exercise instead of one

### ISSUE THREAD

**Issue by christirichards** [nutritionfactsorg/daily-dozen-ios#20]
We have quite a few users who are requesting that we break up the current single serving for exercise into three servings. Doing this will give our users a better sense of achievement upon completion and help them to feel like they are making more progress toward achieving their daily goals.

**Comment by WesDowney** [comment]
I'll give this one a try if you want.

**Comment by christirichards** [comment]
Resolved in PR #22
