### ISSUE TITLE
Measurement unit always reverts to metric

### ISSUE THREAD

**Issue by jvia** [nutritionfactsorg/daily-dozen-ios#25]
The serving size unit always switches to metric even after I choose imperial. It would be nice if the unit would stay what I selected.

**Comment by eragmus** [comment]
This problem has still not ben fixed.

**Comment by eragmus** [comment]
This problem has still not been fixed.

**Comment by christirichards** [comment]
This issue is being addressed in the upcoming version of the app.

**Comment by marc-medley** [comment]
Fix checked into `version_3` branch. Will be include in next release.

**Comment by marc-medley** [comment]
Version 3.0.0 has with this fixed has been pubished via the App Store. If the `UserDefaults.standard.object(forKey: SettingsKeys.unitsTypePref)` has not been previously set, then the default is set to Imperial.

**Comment by qw151100** [comment]
nice!!
Carol Poole
480-825-0097
