### ISSUE TITLE
IOS App not available in german Itunes

### ISSUE THREAD

**Issue by hw153** [nutritionfactsorg/daily-dozen-ios#26]
Hello there, unfortunately (I tried 3 different iphones/ipads) I cant download the IOS app from a geolocation in germany, the app does not show up in the search results. when use the direct link 

https://nutritionfacts.org/daily-dozen-challenge/ 

I can at least download the english version. 

Could  this be due to the lack of a german translation, my geoposition,  or something completely diferent?

with best regards, 
Hans

**Comment by marc-medley** [comment]
@hw153 The Daily Dozen iOS "Teritory Availability" is set to All which expressly includes Germany. Please check if the following link works for you. Thanks.

<https://apps.apple.com/us/app/dr-gregers-daily-dozen/id1060700802>

**Comment by marc-medley** [comment]
The English speaking version is available internationally to all regions.  The currently released (DailyDozen iOS v 3.2.3) languages are English and Spanish.

Localized translations for both Android and iOS is being handled through [nutritionfactsorg/daily-dozen-localization](https://github.com/nutritionfactsorg/daily-dozen-localization). The localizations are going through translation and/or review by human translators. Each localized language version will be added as completed. 

Please see `daily-dozen-localization` for more details. The `daily-dozen-localization` readme also contains links to various regional app store pages for the Daily Dozen app.

Issues related to localized and translation can be submitted a [daily-dozen-localization/issue](https://github.com/nutritionfactsorg/daily-dozen-localization/issues).

**Comment by marc-medley** [comment]
@hw153 As FYI, [iOS Daily Dozen with German translation](https://apps.apple.com/de/app/dr-gregers-daily-dozen/id1060700802) has been released.

If you find any translation issues, these can be reported as a [nutritionfactsorg/daily-dozen-localization/issue](https://github.com/nutritionfactsorg/daily-dozen-localization/issues). The `nutritionfactsorg/daily-dozen-localization` repository is used coordinate the translations for both the Daily Dozen for the Android and Apple devices. If you find a non-translation issue with the Apple iOS application itself, then that issue can be reported here to this `daily-dozen-ios` repository.
