### ISSUE TITLE
Add Iodine and Omega 3?

### ISSUE THREAD

**Issue by kjmoon** [nutritionfactsorg/daily-dozen-ios#28]
Since Vitamin B12 and D are on the list, any thoughts on adding Iodine and Omega 3 per https://nutritionfacts.org/2011/09/12/dr-gregers-2011-optimum-nutrition-recommendations/ ?

**Comment by JoshuaStorm** [comment]
I had similar thoughts, as I added an algae omega 3 to my morning supplements list. 

Maybe we could add a "Add Category" option for those of us who want to expand on the Daily Dozen?

**Comment by eragmus** [comment]
This issue has still not been addressed.

**Comment by christirichards** [comment]
Plant-based Omega 3 is currently being added to the app. We are not looking to add in iodine at this time.
