### ISSUE TITLE
21 Tweaks data retention issues

### ISSUE THREAD

**Issue by nikki686** [nutritionfactsorg/daily-dozen-ios#35]
The 21 Tweaks wipes its data.  The data has to be entered twice before it retains it.  In particular, the weight always has to be entered twice before it populates and retains the tick-box.   When flicking between the 21 Tweaks and the Daily Dozen the app doesnt retain the date selected and defaults back to today so the date has to be manually reselected each time.  This should be a parameter-passing fix if the two apps can pass data.

**Comment by nikki686** [comment]
If you can look at further development to integrate the two apps better.  It would also be good if the user ticks all of the beverages boxes in the Daily Dozen app it automatically updates the 21 tweaks with a tick in the Stay Hydrated box.

**Comment by marc-medley** [comment]
@nikki686 The 21 Tweaks data retention issues reported here should now be resolved in the v3.2.1(5) which has been checked into the master branch.

**Comment by nikki686** [comment]
Hi, I just used the 21 tweaks and it's still losing data after I exit the app.  Do I need to uninstall and reinstall it to capture the updates or will they happen automatically at some point?  Thanks

**Comment by marc-medley** [comment]
@nikki686 Are you using the 21 Tweaks v3.1.0 which is currently in the App Store? or, by building and running v3.2.1(5) from this repository via Xcode? Version v3.2.1(5) is still has a review process to complete before it will be available in Apple's App Store.

**Comment by nikki686** [comment]
@marc-medley I'm just using the App Store v3.1.0 download version.  I'll wait for the official release before using it again.  It just keeps losing all of the ticks from the boxes at present.  I don't know if it still retains data in the backend and so somewhat superficial or if loss of ticks equates to loss of data for populating the graphs and tracking history.

**Comment by marc-medley** [comment]
@nikki686 

> ... you could backfill the ticks by selecting the end tick in the series but not on the ios platform. Is that the limitation of the dev environment or just different coding?

The backfill was a difference in coding between Android and iPhone. App Store v3.1.0 did introduce a fill to left-most tick to match the Android fill direction. (The direction is programmable, but currently set from right to left). Earlier versions required that each box be checked individually.

I'll circle back around after v3.2.1 is published through the App Store to check how the updated app is working for you.

**Comment by marc-medley** [comment]
@nikki686 Daily Dozen v3.2.1 (build 7) has been [released in the Apple App Store](https://apps.apple.com/gb/app/dr-gregers-daily-dozen/id1060700802). Your feedback would be welcome.

**Comment by marc-medley** [comment]
@nikki686 I'm closing this issue since no 21 Tweaks data retention concerns have been reported since the Daily Dozen v3.2.1 [Apple App Store](https://apps.apple.com/gb/app/dr-gregers-daily-dozen/id1060700802) release.  This issue can be reopened or another issue created if needed.

**Comment by nikki686** [comment]
Thanks Marc,  I'll reinstall at some point in the future.
