### ISSUE TITLE
Add in the ability to toggle different units of measurements for categories

### ISSUE THREAD

**Issue by christirichards** [nutritionfactsorg/daily-dozen-ios#4]
The current categories list servings in cups/spoons.  It has been highly requested that this information could be toggled to grams and (in the future) other units of measurement.

**Comment by pramsey1234** [comment]
Might be obvious but don't forget that using weight rather than volume will not just be a conversion but alternative data since things have different densities and packing. Might be nice to start collecting the data somewhere so that the developer won't have to do all of the kitchen work.

**Comment by christirichards** [comment]
Resolved in the latest update.
