### ISSUE TITLE
Links (such as turnip greens) are broken

### ISSUE THREAD

**Issue by abhartia** [nutritionfactsorg/daily-dozen-ios#53]

**Comment by marc-medley** [comment]
@abhartia The "turnip" video topic had recently been removed from the website causing the app link to no longer be valid.  

What the topic link used to show can be viewed on archive.org: 

• [English: topics/turnips](https://web.archive.org/web/20210119031115/nutritionfacts.org/topics/turnips/)
• [Spanish: es/topics/nabos](https://web.archive.org/web/20200815085008/https://nutritionfacts.org/es/topics/nabos/)

An update has been checked in to remove the no longer existant link. The update will go out with the next iOS app release. 

Thanks for the report.

**Comment by marc-medley** [comment]
There are, at this time, 36 links which will be updated in the next release.  

A URL checker has now been added to the automatic the . The utility is located in [daily-dozen-localization/Utilities/UrlCheck](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Utilities/UrlCheck).

The current report can be found at [daily-dozen-localization/Utilities/UrlCheck/Report.md](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Utilities/UrlCheck/Report.md).

**Comment by marc-medley** [comment]
links verified to match with current NutritionFacts.org with the release of v3.2.9
