### ISSUE TITLE
Contributing: Google Services Info.plist file

### ISSUE THREAD

**Issue by jake-ruth** [nutritionfactsorg/daily-dozen-ios#73]
Hello, I am interested in contributing and trying to get the project up and running but it looks like I need the Google Services info plist file. How do I obtain it? I don't see anything in the readme etc. Thank you!

**Comment by marc-medley** [comment]
`GoogleService-Info.plist` is not required for a development build if the file reference is removed from the project and the Firebase Analytic code sections are wrapped with `#if` `#endif`.

``` swift
#if DEBUG
print("ANALYTICS is disabled in development mode")
#else
FirebaseApp.configure()
…
#endif
```

The `GoogleService-Info.plist` file itself is not being distributed for open source use.

**Comment by jamie-brannan** [comment]
Would an alternative scheme for the project be of interest?
